FROM python:3.12-slim

WORKDIR /app
COPY requirement.txt .
RUN sed -i 's|http://deb.debian.org/debian|http://mirror.yandex.ru/debian|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirement.txt
COPY . .

CMD ["uvicorn", "service2:app", "--host", "0.0.0.0", "--port", "8224"]