apiVersion: v2
name: items-app
description: Helm chart for items-svc-s16 (Week 13)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - items
  - fastapi
  - kubernetes
maintainers:
  - name: Viktoriya Pavlova
    email: s16@siguti.ru