# Prod: 3 реплики
replicaCount: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

probes:
  liveness:
    initialDelaySeconds: 30
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 5

image:
  tag: "v1.0.0"
  pullPolicy: Always

env:
  DEBUG: "false"
  LOG_LEVEL: "info"