events { worker_connections 1024; }

http {
    upstream sessions_backend {
        server sessions-svc:8107;
    }

    server {
        listen 80;

        # Проксирование /products/ → /products/
        location /products/ {
            proxy_pass http://sessions_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Health check гейта
        location /health {
            access_log off;
            return 200 "gateway-ok\n";
            add_header Content-Type text/plain;
        }

        # Дефолт
        location / {
            return 404 "Not Found\n";
            add_header Content-Type text/plain;
        }
    }
}